language: php
php:
  - 7.2
before_script: composer install
script:
    - ./vendor/bin/phpunit tests/
after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
notifications:
  email: false
